### PR TITLE
Nomonde- Added text 

### PR DESCRIPTION
**Pull request by nomondemadlala**
##Demo

Add text to the content view
Screenshot_20231212_161850

### CODE REVIEW

**Review by SKopoloza895 — CHANGES_REQUESTED** [review]
Please change the text

**Review by SKopoloza895 — APPROVED** [review]

**Comment by nomondemadlala** [comment]
Good morning Siyanda

**Comment by nomondemadlala** [comment]
Please check sale list today final

**Comment by nomondemadlala** [comment]
Please fast

**Pull request merged**
